# Generated by Django 5.0.4 on 2024-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
                ('Documento', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_endereco', models.CharField(max_length=10)),
                ('Cep', models.CharField(max_length=8)),
                ('Uf', models.CharField(max_length=2)),
                ('Bairro', models.CharField(max_length=30)),
                ('Cidade', models.CharField(max_length=30)),
                ('Logradouro', models.CharField(max_length=30)),
                ('Numero', models.IntegerField(max_length=5)),
            ],
        ),
    ]
