# Generated by Django 5.0.4 on 2024-04-07 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='Codigo_endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='Codigo_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Documento',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
